
=head1 NAME

Poet - A Mason + PSGI web framework

=head1 SYNOPSIS

  % poet new -a MyApp -d my_app  # Generate a Poet application called MyApp in my_app

=head1 DESCRIPTION

Poet is a web framework for Mason developers.

Poet relies on PSGI/Plack for server integration and web APIs, and Mason for
request routing and templating. It just adds conventions and utilities to glue
them together intelligently, based on the author's best practices from 15+
years of Mason site development.  Poet is by itself a minimal framework, but is
easily extended with subclasses and roles.

Some things that Poet provides:

=over

=item *

A standard useful directory hierarchy for web sites (C<bin>, C<comps>, C<conf>,
C<lib>, etc.)

=item *

Auto-initialization of the environment from any script inside the directory
hierarchy.

=item *

A multi-file configuration layout with knowledge of different application
"layers" (eg. development, staging and production).

=item *

Easy one-line access to configuration, caching and logging objects.

=back
