
=head1 NAME

Poet::Manual - Index of Poet documentation

=head1 MANUALS

=over

=item L<Poet::Manual::Tutorial>

Provides a tour of Poet by showing how to build a micro-blog website.

=item L<Poet::Manual::Intro>

An introduction to Poet features with links to other documentation.

=item L<Poet::Manual::Configuring>

A list of Poet configuration options.

=item L<Poet::Manual::Subclassing>

A guide to customizing Poet behavior via subclassing.

=back

=head1 REFERENCE DOCUMENTATION

=over

=item L<Poet::Environment>

=item L<Poet::Conf>

=item L<Poet::Mason>

=item L<Poet::Log>

=item L<Poet::Cache>

=back
