
=head1 NAME

Poet::Manual - Index of Poet documentation

=head1 MANUALS

=over

=item L<Poet::Manual::Tutorial>

Provides a tour of Poet by showing how to build a micro-blog application.

=item L<Poet::Manual::Devel>



=back

=head1 REFERENCE DOCUMENTATION

=over

=item L<Poet>

=item L<Poet::Script>

=item L<Poet::Environment>

=item L<Poet::Conf>

=back
